name: CI

on:
  schedule:
    - cron: '0 11 * * *'
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

env:
  IMAGE_NAME: 'zerosuxx/k0d'
  PLATFORMS: 'linux/amd64,linux/arm64'
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and deploy docker image
        if: !startsWith(github.ref, 'refs/tags')
        run: |
          export KUBECTL_VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt | cut -c2-)
          export HELM_VERSION=$(curl -s https://scripts.zer0.hu/lv | sh -s helm/helm | cut -c2-)
          export HELMFILE_VERSION=$(curl -s https://scripts.zer0.hu/lv | sh -s helmfile/helmfile | cut -c2-)
          export K9S_VERSION=$(curl -s https://scripts.zer0.hu/lv | sh -s derailed/k9s | cut -c2-)
          export EXTRA_ARGS='--build-arg="KUBECTL_VERSION=${KUBECTL_VERSION}" --build-arg="HELM_VERSION=${HELM_VERSION}" --build-arg="HELMFILE_VERSION=${HELMFILE_VERSION}" --build-arg="K9S_VERSION=${K9S_VERSION}"'
          make build-and-push TAG=latest TARGET=base 
          make build-and-push TAG=debug TARGET=debug

      - name: Build and deploy docker image with tag
        if: startsWith(github.ref, 'refs/tags')
        run: |
          export VERSION=$(git describe --tags 2>/dev/null || echo '0.1.0')
          echo ${VERSION}
          make build-and-push TAG=${VERSION} TARGET=base
          make build-and-push TAG=${VERSION}-debug TARGET=debug
        
