name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

env:
  IMAGE_NAME: 'zerosuxx/example'
  PLATFORMS: 'linux/amd64,linux/arm64'
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Build and deploy docker image
        run: |
          export VERSION=$(git describe --tags 2>/dev/null || echo '0.1.0')
          echo $VERSION
          docker buildx build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ${{ env.IMAGE_NAME }}:latest \
            --platform ${{ env.PLATFORMS }} \
            --push \
            --tag ${{ env.IMAGE_NAME }}:$VERSION \
            --tag ${{ env.IMAGE_NAME }}:latest \
            .
